# config/config.yaml
paths:
  git_root: auto  # Will be determined automatically
  data_subfolder: "data"
  gps_folder: "GPS/Senegal/2023"
  gps_file: "SNGE8RFL.shp"
  wealth_index_file: "Wealth_Index_DF.csv"
  shapefile_folder: "ShapeFiles/Senegal_Shapefile"
  shapefile: "gadm41_SEN_0.shp"
  output_folder: "data/Results/GPSResults"
  output_file: "output.gpkg"

processing:
  urban_buffer: 2000  # meters
  rural_buffer: 5050  # meters
  cell_size: 500     # meters
  crs:
    input: 4326      # WGS84
    processing: 32628 # UTM

visualization:
  figsize: [15, 15]
  dpi: 300
  basemap: "CartoDB.Positron"