# Information needed for each country
countries: 
  - name: "Senegal" # Named country
    iso: "SEN" # The 3-letter ISO code to be used for file names
    years: [2024, 2023, 2019, 2018, 2017, 2016]  # Years to process for the country
    crs: "EPSG:32628" # The crs to be used

  - name: "Ghana"
    iso: "GHA"
    years: [2022]
    crs: "EPSG:32630" 

# Information for building the grid for a country
cell_size_km: 5 # Length of each grid cell
min_area_percent: 40.0 # Minimum area of overlap with Senegal to keep the grid cell

# Download information
sentinel:
  bands: ["B2", "B3", "B4", "B8", "B5", "B6", "B7", "B11", "B12"] # Bands needed
  cloud_threshold: 20 # Threshold of clouds to use image in aggregates
  composite_method: "median" # Method to create an annual composite

viirs:
  bands: ["avg_rad"] # Bands used
  composite_method: "median"  # Method to create annual composite

# Utilities
log_level: "INFO" #Setup log_level

max_workers: -2 # For threading (-2 means all workers minus 1)
verbose: 10 # Level of detail