countries:
  - name: "Senegal"
    iso: "SEN"
    years: [2019, 2023, 2018, 2024] #2017,2016,2015
    crs: "EPSG:32628"
    validate_files: True
    validation_sample_ratio: 0.2

  #- name: "Ghana"
    #iso: "GHA"
    #years: [2022]
    #crs: "EPSG:32630" 

log_level: "INFO"

cell_size_km: 5
min_area_percent: 40.0

max_workers: -2
verbose: 10


sentinel:
  bands: ["B2", "B3", "B4", "B8", "B5", "B6", "B7", "B11", "B12"]
  cloud_threshold: 20
  composite_method: "median"


# Add this section to your existing config.yaml
viirs:
  collection: "NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG"
  bands: ["avg_rad"]
  temporal_aggregation: "annual"  # Options: "annual", "monthly"
  composite_method: "median"  # Options: "median", "mean"
  sample_points_per_country: 5000  # For normalization statistics