# Output configuration
output_file: "wealth_index"
log_level: "INFO" 

# Data sources configuration
country_year:
  Senegal: 
    - "2023"
    - "2019"
    - "2018"
    - "2017"
    - "2016"
    - "2015"
  Ghana:
    - "2022"

# Data processing configuration
columns_to_include:
  # Household identification and basic characteristics
  - "hv000"  # Country code
  - "hv001"  # Cluster number
  - "hv005"  # Household sample weight
  - "hv007"  # Year of interview
  - "hv009"  # Number of household members
  - "hv014"  # Number of children 5 and under
  - "hv025"  # Urban/rural status
  
  # Water and sanitation
  - "hv201"  # Source of drinking water
  - "hv202"  # Source of non-drinking water
  - "hv204"  # Time to get to water source
  - "hv205"  # Type of toilet facility
  
  # Household characteristics and assets
  - "hv206"  # Has electricity
  - "hv207"  # Has radio
  - "hv208"  # Has television
  - "hv209"  # Has refrigerator
  - "hv210"  # Has bicycle
  - "hv211"  # Has motorcycle/scooter
  - "hv212"  # Has car/truck
  - "hv213"  # Main floor material
  - "hv214"  # Main wall material
  - "hv215"  # Main roof material
  - "hv216"  # Number of rooms
  - "hv217"  # Relationship structure
  - "hv219"  # Sex of head of household
  - "hv220"  # Age of head of household
  - "hv221"  # Has telephone
  
  # Additional household assets and characteristics
  - "hv225" # Share toilet with other households
  - "hv226" # Type of cooking fuel
  - "hv227" # Has mosquito bed net for sleeping
  - "hv228" # Children under 5 slept under mosquito bed net l
  - "hv230a" # Place where household members wash their hands
  - "hv230b" # Presence of water at hand washing place
  - "hv232" # Items present: Soap or detergent
  - "hv232b" # Items present: Ash, mud, sand
  - "hv232y" # Items present: None
  - "hv234a" # Result of salt test for iodine
  - "hv235" # Location of source for water
  
  # Water treatment
  - "hv237" # Anything done to water to make safe to drink
  - "hv237a" # Water usually treated by: boil
  - "hv237b" # Water usually treated by: add bleach/chlorine
  - "hv237c" # Water usually treated by: strain through a clot
  - "hv237d" # Water usually treated by: use water filter
  - "hv237e" # Water usually treated by: solar disinfection
  - "hv237f" # Water usually treated by: let it stand and sett
  - "hv237x" # Water usually treated by: other
  - "hv237z" # Water usually treated by: don't know
  
  # More household characteristics
  - "hv238" # Number of households sharing toilet
  - "hv240" # Stove has a chimney 
  - "hv241" # Food cooked in the house/ separate building/ ou
  - "hv242" # Household has separate room used as kitchen
  
  # Additional variables
  - "hv243a" # Has mobile telephone
  - "hv243b" # Has watch 
  - "hv243c" # Has animal-drawn cart 
  - "hv243d" # Has boat with a motor
  - "hv244" # Owns land usable for agriculture 
  - "hv245" # Hectares of agricultural land (1 decimal)
  - "hv246" # Owns livestock, herds or farm animals
  - "hv246a" # Owns cattle
  - "hv246b" # Owns cows/ bulls 
  - "hv246c" # Owns horses/ donkeys/ mules
  - "hv246d" # Owns goats 
  - "hv246e" # Owns sheep
  - "hv246f" # Owns chickens/poultry
  - "hv246g" # Owns camels
  - "hv246h" # Owns pork
  - "hv247" # Has bank account
  - "hml1" # Number of mosquito bed nets
  - "hml2" # Number of children under mosquito bed net previ

# Value replacement configuration
replace_val:
  unknown: .nan
  none: 0
  "95 or more": 95
  "don't know": .nan
  "nan": .nan


missing_threshold: 0.5

# Analysis configuration
imputation: "compare"
verbose: 5 # The level of detail returned by Parallel. 0 is none, 10 is high for debugging but technically goes up to 100
skip_optimizing: False 

# FAMD analysis configuration
n_simulations: 1000
plot_contributions: True
run_parallel_analysis: True
iqr_multiplier: 2
normalize_index: True

n_jobs: -1 # Can be set as -1 to use all cores, or -2 for all cores except 1
