# config.yaml

countries:
  - name: "Senegal"
    iso2: "SN"
    crs: "EPSG:32628" # UTM Zone 28N in meters
    years: [2023,2019,2018,2017,2016,2015]
  
  - name: "Ghana"
    iso2: "GH"
    crs: "EPSG:32630"  # UTM Zone 30N in meters
    years: [2022]
  

default_crs: "EPSG:4326"  # WGS84 in degrees

wealth_index: wealth_index.parquet


cell_size: 500  # meters

buffer:
  urban: 2000     # meters
  rural: 5050     # meters

visualization:
  figsize: [15, 15]
  dpi: 300

verbose: 5
n_jobs: -1
log_level: "INFO"