# Configuration for wealth index coverage threshold analysis
min_threshold: 30  # Minimum coverage threshold percentage to analyze
max_threshold: 35  # Maximum coverage threshold percentage to analyze
threshold_steps: 20 # Number of steps between max and min threshold