# config/config.yaml
paths:
  git_root: auto  # Will be determined automatically
  data_subfolder: "data"
  wealth_index_formats:
    - "wealth_index.parquet"
    - "wealth_index.csv"

processing:
  urban_buffer: 2000  # meters
  rural_buffer: 5050  # meters
  cell_size: 500     # meters
  crs:
    input: 4326      # WGS84

visualization:
  figsize: [15, 15]
  dpi: 300
  basemap: "CartoDB.Positron"
  colormap:
    type: "RdYlBu"
    steps: 11
    reverse: true
  output_format: "png"